format = """
$username\
$hostname\
$directory\
$git_branch\
$git_status\
$fill\
$c\
$elixir\
$elm\
$golang\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
$scala\
$conda\
$python\
$time\n  \
[ó±ª](fg:mindaro) \
"""

palette = "nahida"

[palettes.nahida]
overlay = '#30523d'
aquamarine = '#6febab'
crayola = '#c5f677'
teagreen = '#d3ebba'
eucalyptus  = '#44ffb4'
spring = '#24f795'
mindaro = '#d2ff8f'

[directory]
format = "[î‚¶](fg:overlay)[ $path ]($style)[î‚´](fg:overlay) "
style = "bg:overlay fg:eucalyptus "
truncation_length = 3
truncation_symbol = "â€¦/"

[directory.substitutions]
Documents = "ó°ˆ™"
Downloads = "ï€™ "
Music = "ï€ "
Pictures = "ï€¾ "

[fill]
style = "fg:overlay"
symbol = " "

[git_branch]
format = "[î‚¶](fg:overlay)[ $symbol $branch ]($style)[î‚´](fg:overlay) "
style = "bg:overlay fg:spring"
symbol = "ï˜"

[git_status]
disabled = false
style = "bg:overlay fg:aquamarine"
format = '[î‚¶](fg:overlay)([$all_status$ahead_behind]($style))[î‚´](fg:overlay) '
up_to_date = '[ âœ“ ](bg:overlay fg:mindaro)'
untracked = '[?\($count\)](bg:overlay fg:crayola)'
stashed = '[\$](bg:overlay fg:mindaro)'
modified = '[!\($count\)](bg:overlay fg:crayola)'
renamed = '[Â»\($count\)](bg:overlay fg:mindaro)'
deleted = '[âœ˜\($count\)](style)'
staged = '[++\($count\)](bg:overlay fg:crayola)'
ahead = '[â‡¡\(${count}\)](bg:overlay fg:spring)'
diverged = 'â‡•[\[](bg:overlay fg:mindaro)[â‡¡\(${ahead_count}\)](bg:overlay fg:spring)[â‡£\(${behind_count}\)](bg:overlay fg:teagreen )[\]](bg:overlay fg:mindaro)'
behind = '[â‡£\(${count}\)](bg:overlay fg:teagreen )'

[time]
disabled = false
format = "[î‚¶](fg:overlay)[ $time ó°´ˆ ]($style)[î‚´ ](fg:overlay)"
style = "bg:overlay fg:teagreen "
time_format = "%I:%M%P"
use_12hr = true

[username]
disabled = false
format = "[î‚¶](fg:overlay)[ ó°§± $user ]($style)[î‚´](fg:overlay) "
show_always = true
style_root = "bg:overlay fg:mindaro"
style_user = "bg:overlay fg:mindaro"

[hostname]
disabled = false
format = "[î‚¶](fg:overlay)[ ïŒš $hostname ]($style)[î‚´](fg:overlay) "
style = "bg:overlay fg:teagreen "
ssh_only = false

# Languages

[c]
style = "bg:overlay fg:eucalyptus "
format = "[î‚¶](fg:overlay)[$symbol$version]($style)[î‚´](fg:overlay) "
disabled = false
symbol = "î˜ "

[elixir]
style = "bg:overlay fg:eucalyptus "
format = "[î‚¶](fg:overlay)[$symbol$version]($style)[î‚´](fg:overlay) "
disabled = false
symbol = "î‰µ "

[elm]
style = "bg:overlay fg:eucalyptus "
format = "[î‚¶](fg:overlay)[$symbol$version]($style)[î‚´](fg:overlay) "
disabled = false
symbol = "î˜¬ "

[golang]
style = "bg:overlay fg:eucalyptus "
format = "[î‚¶](fg:overlay)[$symbol$version]($style)[î‚´](fg:overlay) "
disabled = false
symbol = "î˜§ "

[haskell]
style = "bg:overlay fg:eucalyptus "
format = "[î‚¶](fg:overlay)[$symbol$version]($style)[î‚´](fg:overlay) "
disabled = false
symbol = "î· "

[java]
style = "bg:overlay fg:eucalyptus "
format = "[î‚¶](fg:overlay)[$symbol$version]($style)[î‚´](fg:overlay) "
disabled = false
symbol = "î‰– "

[julia]
style = "bg:overlay fg:eucalyptus "
format = "[î‚¶](fg:overlay)[$symbol$version]($style)[î‚´](fg:overlay) "
disabled = false
symbol = "î˜¤ "

[nodejs]
style = "bg:overlay fg:eucalyptus "
format = "[î‚¶](fg:overlay)[$symbol$version]($style)[î‚´](fg:overlay) "
disabled = false
symbol = "ó°™ "

[nim]
style = "bg:overlay fg:eucalyptus "
format = "[î‚¶](fg:overlay)[$symbol$version]($style)[î‚´](fg:overlay) "
disabled = false
symbol = "ó°†¥ "

[rust]
style = "bg:overlay fg:eucalyptus "
format = "[î‚¶](fg:overlay)[$symbol$version]($style)[î‚´](fg:overlay) "
disabled = false
symbol = "î¨"

[scala]
style = "bg:overlay fg:eucalyptus "
format = "[î‚¶](fg:overlay)[$symbol$version]($style)[î‚´](fg:overlay) "
disabled = false
symbol = "îœ· "

[python]
style = "bg:overlay fg:eucalyptus "
format = "[î‚¶](fg:overlay)[$symbol$version]($style)[î‚´](fg:overlay) "
disabled = false
symbol = 'îœ¼ '

[conda]
style = "bg:overlay fg:eucalyptus "
format = "[î‚¶](fg:overlay)[$symbol$environment]($style)[î‚´](fg:overlay) "
disabled = false
symbol = 'ğŸ…’ '
